routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\AuthenticatedSessionController;
use App\Http\Controllers\DataTableController;
use App\Http\Controllers\ImageController;
use App\Http\Controllers\NewsController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\RouteController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

# ------ Unauthenticated routes ------ #
Route::get('/', [RouteController::class, 'wushuHome']);
Route::name('wushu.')->group(function(){
    Route::get('/news', [RouteController::class, 'wushuNews'])->name('news');
    Route::get('/news/detail/{newsId}', [RouteController::class, 'wushuNewsDetail'])->name('news-detail');
    Route::get('/galeries', [RouteController::class, 'wushuGaleries'])->name('galeries');
    Route::get('/galeries/detail/{galeryId}', [RouteController::class, 'wushuGaleriesDetail'])->name('galeries-detail');
    Route::get('/about/{who}', [RouteController::class, 'wushuAbout'])->name('about');
    Route::get('/competition/{what}', [RouteController::class, 'wushuCompetition'])->name('competition');
});
require __DIR__.'/auth.php';


# ------ Authenticated routes ------ #
Route::middleware('auth')->prefix('dashboard')->group(function() {
    Route::get('/', [RouteController::class, 'dashboard'])->name('home'); # dashboard

    Route::prefix('profile')->group(function(){
        Route::get('/', [ProfileController::class, 'myProfile'])->name('profile');
        Route::put('/change-ava', [ProfileController::class, 'changeFotoProfile'])->name('change-ava');
        Route::put('/change-profile', [ProfileController::class, 'changeProfile'])->name('change-profile');
    }); # profile group

    # ------ DataTables routes ------ #
    Route::prefix('data')->name('datatable.')->group(function(){
        Route::get('/users', [DataTableController::class, 'getUsers'])->name('users');
    });

    Route::resource('users', UserController::class);
    Route::resource('news', NewsController::class);
    Route::resource('galeries', ImageController::class);
});

app/Models/News.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class News extends Model
{
    use HasFactory;

    protected $fillable = [
        'title',
        'image',
        'content'
    ];
}

app/Http/Controllers/NewsController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
use App\Http\Requests\RequestStoreOrUpdateNews;
use App\Models\News;
use Illuminate\Support\Facades\Hash;

class NewsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $news = News::orderByDesc('id');
        $news = $news->paginate(50);

        return view('dashboard.news.index', compact('news'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.news.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(RequestStoreOrUpdateNews $request)
    {
        $validated = $request->validated() + [
            'created_at' => now(),
        ];

        $validated['image'] = 'default.png';
        if($request->hasFile('image')){
            $fileName = time() . '.' . $request->image->extension();
            $validated['image'] = $fileName;
            // move file
            $request->image->move(public_path('uploads/images'), $fileName);
        }

        $news = News::create($validated);

        return redirect(route('news.index'))->with('success', 'News berhasil ditambahkan.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return News::findOrFail($id);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $news = News::findOrFail($id);

        return view('dashboard.news.edit', compact('news'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(RequestStoreOrUpdateNews $request, $id)
    {
        $validated = $request->validated() + [
            'updated_at' => now(),
        ];

        $news = News::findOrFail($id);

        $validated['image'] = $news->image;

        if($request->hasFile('avatar')){
            $fileName = time() . '.' . $request->image->extension();
            $validated['image'] = $fileName;

            // move file
            $request->image->move(public_path('uploads/images'), $fileName);
            
            // delete old file
            $oldPath = public_path('/uploads/images/'.$news->image);
            if($news->image && file_exists($oldPath) && $news->image != 'default.png'){
                unlink($oldPath);
            }
        }

        $news->update($validated);

        return redirect(route('news.index'))->with('success', 'News berhasil diperbarui.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $news = News::findOrFail($id);
        // delete old file
        $oldPath = public_path('/uploads/images/'.$news->image);
        if($news->image && file_exists($oldPath) && $news->image != 'default.png'){
            unlink($oldPath);
        }
        $news->delete();

        return redirect(route('news.index'))->with('success', 'News berhasil dihapus.');
    }
}

resources/views/dashboard/news/create.blade.php
@extends('layouts.app')
@section('title', 'Tambah Data News')

@section('title-header', 'Tambah Data News')
@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{ route('home') }}">Dashboard</a></li>
    <li class="breadcrumb-item"><a href="{{ route('news.index') }}">Data News</a></li>
    <li class="breadcrumb-item active">Tambah Data News</li>
@endsection

@section('c_css')
<script src="https://cdn.ckeditor.com/4.19.0/full-all/ckeditor.js"></script>
@endsection

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card shadow">
                <div class="card-header bg-transparent border-0 text-dark">
                    <h5 class="mb-0">Formulir Tambah Data News</h5>
                </div>
                <div class="card-body">
                    <form action="{{ route('news.store') }}" method="POST" role="form" enctype="multipart/form-data">
                        @csrf

                        <div class="form-group mb-3">
                            <label for="title">Title</label>
                            <input type="text" class="form-control @error('title') is-invalid @enderror" id="title"
                                placeholder="Title News" value="{{ old('title') }}" name="title">

                            @error('title')
                                <div class="d-block invalid-feedback">{{ $message }}</div>
                            @enderror
                        </div>

                        <div class="form-group mb-3">
                            <label for="content">Content</label>
                            <textarea  class="form-control @error('content') is-invalid @enderror" id="ckeditor-backend"
                            placeholder="Content News" name="content" cols="30" rows="10">{!! old('content') !!}</textarea>
                            @error('content')
                                <div class="d-block invalid-feedback">{{ $message }}</div>
                            @enderror
                        </div>

                        <div class="form-group mb-3">
                            <label for="image">Image Thumbnail</label>
                            <input type="file" class="form-control dropify-media @error('image') is-invalid @enderror"
                                id="image" placeholder="Image Thumbnail News"
                                name="image">

                            @error('image')
                                <div class="d-block invalid-feedback">{{ $message }}</div>
                            @enderror
                        </div>

                        <div class="row">
                            <div class="col-6">
                                <button type="submit" class="btn btn-sm btn-primary">Tambah</button>
                                <a href="{{route('news.index')}}" class="btn btn-sm btn-secondary">Kembali</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script>
        CKEDITOR.replace('ckeditor-backend')
        $('.dropify-media').dropify({
            messages: {
                default: 'Drag and drop a file here or click',
                replace: 'Drag and drop or click to replace',
                remove: 'Remove',
                error: 'Ooops, something wrong happended.'
            },
        });
    </script>
@endsection

resources/views/dashboard/news/edit.blade.php
@extends('layouts.app')
@section('title', 'Ubah Data News')

@section('title-header', 'Ubah Data News')
@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{ route('home') }}">Dashboard</a></li>
    <li class="breadcrumb-item"><a href="{{ route('news.index') }}">Data News</a></li>
    <li class="breadcrumb-item active">Ubah Data News</li>
@endsection

@section('c_css')
<script src="https://cdn.ckeditor.com/4.19.0/full-all/ckeditor.js"></script>
@endsection

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card shadow">
                <div class="card-header bg-transparent border-0 text-dark">
                    <h5 class="mb-0">Formulir Ubah Data News</h5>
                </div>
                <div class="card-body">
                    <form action="{{ route('news.update', $news->id) }}" method="POST" role="form" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        <div class="form-group mb-3">
                            <label for="title">Title</label>
                            <input type="text" class="form-control @error('title') is-invalid @enderror" id="title"
                                placeholder="Title News" value="{{ old('title', $news->title) }}" name="title">

                            @error('title')
                                <div class="d-block invalid-feedback">{{ $message }}</div>
                            @enderror
                        </div>

                        <div class="form-group mb-3">
                            <label for="content">Content</label>
                            <textarea class="form-control @error('content') is-invalid @enderror" id="ckeditor-backend" placeholder="Content News"
                                name="content" cols="30" rows="10">{!! old('content', $news->content) !!}</textarea>
                            @error('content')
                                <div class="d-block invalid-feedback">{{ $message }}</div>
                            @enderror
                        </div>

                        <div class="form-group mb-3">
                            <label for="image">Image Thumbnail</label>
                            <input type="file" class="form-control dropify-media @error('image') is-invalid @enderror"
                                id="image" placeholder="Image Thumbnail News" name="image" data-default-file="{{ asset('/uploads/images/'.$news->image) }}">

                            @error('image')
                                <div class="d-block invalid-feedback">{{ $message }}</div>
                            @enderror
                        </div>

                        <div class="row">
                            <div class="col-6">
                                <button type="submit" class="btn btn-sm btn-primary">Ubah</button>
                                <a href="{{ route('news.index') }}" class="btn btn-sm btn-secondary">Kembali</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script>
        CKEDITOR.replace('ckeditor-backend')
        $('.dropify-media').dropify({
            messages: {
                default: 'Drag and drop a file here or click',
                replace: 'Drag and drop or click to replace',
                remove: 'Remove',
                error: 'Ooops, something wrong happended.'
            },
        }); 
    </script>
@endsection

resources/views/dashboard/news/index.blade.php
@extends('layouts.app')
@section('title', 'News')

@section('title-header', 'News')
@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{ route('home') }}">Dashboard</a></li>
    <li class="breadcrumb-item active">News</li>
@endsection

@section('action_btn')
    <a href="{{route('news.create')}}" class="btn btn-default">Tambah Data</a>
@endsection

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card shadow">
                <div class="card-header bg-transparent border-0 text-dark">
                    <h2 class="card-title h3">News</h2>
                    <div class="table-responsive">
                        <table class="table table-flush table-hover">
                            <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Title</th>
                                    <th>Content</th>
                                    <th>Image Thumbnail</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse ($news as $item)
                                    <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td>{{ $item->title }}</td>
                                        <td>{!! str()->limit($item->content, 30) ?? 'Tidak Ada Konten' !!}</td>
                                        <td>
                                            <img src="{{ asset('/uploads/images/'.$item->image) }}" alt="{{ $item->title }}" width="100">
                                        </td>
                                        <td class="d-flex jutify-content-center">
                                            <a href="{{route('news.edit', $item->id)}}" class="btn btn-sm btn-warning"><i class="fas fa-pencil-alt"></i></a>
                                            <form id="delete-form-{{ $item->id }}" action="{{ route('news.destroy', $item->id) }}" class="d-none" method="post">
                                                @csrf
                                                @method('DELETE')
                                            </form>
                                            <button onclick="deleteForm('{{$item->id}}')" class="btn btn-sm btn-danger"><i class="fas fa-trash"></i></button>
                                        </td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td colspan="3">Tidak ada data</td>
                                    </tr>
                                @endforelse
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th colspan="4">
                                        {{ $news->links() }}
                                    </th>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script>
        function deleteForm(id){
            Swal.fire({
                title: 'Hapus data',
                text: "Anda akan menghapus data!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                cancelButtonText: 'Batal!'
                }).then((result) => {
                if (result.isConfirmed) {
                    $(`#delete-form-${id}`).submit()
                }
            }) 
        }
    </script>
@endsection