routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\AuthenticatedSessionController;
use App\Http\Controllers\DataTableController;
use App\Http\Controllers\ImageController;
use App\Http\Controllers\NewsController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\RouteController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

# ------ Unauthenticated routes ------ #
Route::get('/', [RouteController::class, 'wushuHome']);
Route::name('wushu.')->group(function(){
    Route::get('/news', [RouteController::class, 'wushuNews'])->name('news');
    Route::get('/news/detail/{newsId}', [RouteController::class, 'wushuNewsDetail'])->name('news-detail');
    Route::get('/galeries', [RouteController::class, 'wushuGaleries'])->name('galeries');
    Route::get('/galeries/detail/{galeryId}', [RouteController::class, 'wushuGaleriesDetail'])->name('galeries-detail');
    Route::get('/about/{who}', [RouteController::class, 'wushuAbout'])->name('about');
    Route::get('/competition/{what}', [RouteController::class, 'wushuCompetition'])->name('competition');
});
require __DIR__.'/auth.php';


# ------ Authenticated routes ------ #
Route::middleware('auth')->prefix('dashboard')->group(function() {
    Route::get('/', [RouteController::class, 'dashboard'])->name('home'); # dashboard

    Route::prefix('profile')->group(function(){
        Route::get('/', [ProfileController::class, 'myProfile'])->name('profile');
        Route::put('/change-ava', [ProfileController::class, 'changeFotoProfile'])->name('change-ava');
        Route::put('/change-profile', [ProfileController::class, 'changeProfile'])->name('change-profile');
    }); # profile group

    # ------ DataTables routes ------ #
    Route::prefix('data')->name('datatable.')->group(function(){
        Route::get('/users', [DataTableController::class, 'getUsers'])->name('users');
    });

    Route::resource('users', UserController::class);
    Route::resource('news', NewsController::class);
    Route::resource('galeries', ImageController::class);
});

app/Models/Image.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Image extends Model
{
    use HasFactory;
    
    protected $fillable = [
        'title',
        'media',
        'parent_id',
        'description'
    ];
}

app/Http/Controllers/ImageController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
use App\Http\Requests\RequestStoreOrUpdateImage;
use App\Models\Image;
use Illuminate\Support\Facades\Hash;

class ImageController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $images = Image::orderByDesc('id');
        $images = $images->paginate(50);

        return view('dashboard.images.index', compact('images'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $parents = Image::whereNull('parent_id')->get(['id','title']);
        return view('dashboard.images.create', compact('parents'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(RequestStoreOrUpdateImage $request)
    {
        $validated = $request->all() + [
            'created_at' => now(),
        ];

        if($request->hasFile('media')){
            $fileName = time() . '.' . $request->media->extension();
            $validated['media'] = $fileName;
            // move file
            $request->media->move(public_path('uploads/images'), $fileName);
        }

        $images = Image::create($validated);

        return redirect(route('galeries.index'))->with('success', 'Image berhasil ditambahkan.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return Image::findOrFail($id);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $image = Image::findOrFail($id);
        $parents = Image::whereNull('parent_id')->get(['id','title']);
        return view('dashboard.images.edit', compact('image', 'parents'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(RequestStoreOrUpdateImage $request, $id)
    {
        $validated = $request->all() + [
            'updated_at' => now(),
        ];

        $images = Image::findOrFail($id);

        $validated['media'] = $images->media;

        if($request->hasFile('media')){
            $fileName = time() . '.' . $request->media->extension();
            $validated['media'] = $fileName;

            // move file
            $request->media->move(public_path('uploads/images'), $fileName);
            
            // delete old file
            $oldPath = public_path('/uploads/images/'.$images->media);
            if($images->media && file_exists($oldPath) && $images->media != 'default.png'){
                unlink($oldPath);
            }
        }

        $images->update($validated);

        return redirect(route('galeries.index'))->with('success', 'Image berhasil diperbarui.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $images = Image::findOrFail($id);

        if(is_null($images->parent_id)){
            $childImages = Image::whereParentId($images->id)->get();
            foreach ($childImages as $key => $image) {
                // delete old file
                $oldPath = public_path('/uploads/images/'.$image->media);
                if($image->media && file_exists($oldPath) && $image->media != 'default.png'){
                    unlink($oldPath);
                }
                $image->delete();
            }
        }

        // delete old file
        $oldPath = public_path('/uploads/images/'.$images->media);
        if($images->media && file_exists($oldPath) && $images->media != 'default.png'){
            unlink($oldPath);
        }
        $images->delete();

        return redirect(route('galeries.index'))->with('success', 'Image berhasil dihapus.');
    }
}

resources/views/dashboard/images/create.blade.php
@extends('layouts.app')
@section('title', 'Tambah Data Galery')

@section('title-header', 'Tambah Data Galery')
@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{ route('home') }}">Dashboard</a></li>
    <li class="breadcrumb-item"><a href="{{ route('galeries.index') }}">Data Galery</a></li>
    <li class="breadcrumb-item active">Tambah Data Galery</li>
@endsection

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card shadow">
                <div class="card-header bg-transparent border-0 text-dark">
                    <h5 class="mb-0">Formulir Tambah Data Galery</h5>
                </div>
                <div class="card-body">
                    <form action="{{ route('galeries.store') }}" method="POST" role="form" enctype="multipart/form-data">
                        @csrf

                        <div class="form-group mb-3">
                            <label for="title">Title</label>
                            <input type="text" class="form-control @error('title') is-invalid @enderror" id="title"
                                placeholder="Title Galery" value="{{ old('title') }}" name="title">

                            @error('title')
                                <div class="d-block invalid-feedback">{{ $message }}</div>
                            @enderror
                        </div>

                        <div class="form-group mb-3">
                            <label for="description">Description</label>
                            <input type="text" class="form-control @error('description') is-invalid @enderror" id="description"
                                placeholder="Description Galery" value="{{ old('description') }}" name="description">

                            @error('description')
                                <div class="d-block invalid-feedback">{{ $message }}</div>
                            @enderror
                        </div>

                        <div class="form-group mb-3">
                            <label for="media">Image Media</label>
                            <input type="file" class="form-control dropify-media @error('media') is-invalid @enderror"
                                id="media" placeholder="Image Media Galery"
                                name="media">

                            @error('media')
                                <div class="d-block invalid-feedback">{{ $message }}</div>
                            @enderror
                        </div>

                        <div class="row">
                            <div class="col-12">
                                <div class="form-group mb-3">
                                    <label for="parent_id">Parent Media</label>
                                    <select class="form-control @error('parent_id') is-invalid @enderror" id="parent_id" name="parent_id">
                                        <option value="" selected>---No Parent---</option>
                                        @foreach ($parents as $parent)
                                            <option value="{{ $parent->id }}" @if (old('parent_id') == $parent->id) selected @endif>
                                                {{ $parent->title ?? '-' }}</option>
                                        @endforeach
                                    </select>
        
                                    @error('parent_id')
                                        <div class="d-block invalid-feedback">{{ $message }}</div>
                                    @enderror
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-6">
                                <button type="submit" class="btn btn-sm btn-primary">Tambah</button>
                                <a href="{{route('galeries.index')}}" class="btn btn-sm btn-secondary">Kembali</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/dashboard/images/edit.blade.php
@extends('layouts.app')
@section('title', 'Ubah Data Galery')

@section('title-header', 'Ubah Data Galery')
@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{ route('home') }}">Dashboard</a></li>
    <li class="breadcrumb-item"><a href="{{ route('galeries.index') }}">Data Galery</a></li>
    <li class="breadcrumb-item active">Ubah Data Galery</li>
@endsection

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card shadow">
                <div class="card-header bg-transparent border-0 text-dark">
                    <h5 class="mb-0">Formulir Ubah Data Galery</h5>
                </div>
                <div class="card-body">
                    <form action="{{ route('galeries.update', $image->id) }}" method="POST" role="form" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        <div class="form-group mb-3">
                            <label for="title">Title</label>
                            <input type="text" class="form-control @error('title') is-invalid @enderror" id="title"
                                placeholder="Title Galery" value="{{ old('title', $image->title) }}" name="title">

                            @error('title')
                                <div class="d-block invalid-feedback">{{ $message }}</div>
                            @enderror
                        </div>

                        <div class="form-group mb-3">
                            <label for="description">Description</label>
                            <input type="text" class="form-control @error('description') is-invalid @enderror" id="description"
                                placeholder="Description Galery" value="{{ old('description', $image->description) }}" name="description">

                            @error('description')
                                <div class="d-block invalid-feedback">{{ $message }}</div>
                            @enderror
                        </div>

                        <div class="form-group mb-3">
                            <label for="media">Image Media</label>
                            <input type="file" class="form-control dropify-media @error('media') is-invalid @enderror"
                                id="media" placeholder="Image Media Galery"
                                name="media">

                            @error('media')
                                <div class="d-block invalid-feedback">{{ $message }}</div>
                            @enderror
                        </div>

                        <div class="row">
                            <div class="col-12">
                                <div class="form-group mb-3">
                                    <label for="parent_id">Parent Media</label>
                                    <select class="form-control @error('parent_id') is-invalid @enderror" id="parent_id" name="parent_id">
                                        <option value="" selected>---No Parent---</option>
                                        @foreach ($parents as $parent)
                                            <option value="{{ $parent->id }}" @if (old('parent_id', $image->parent_id) == $parent->id) selected @endif>
                                                {{ $parent->title ?? '-' }}</option>
                                        @endforeach
                                    </select>
        
                                    @error('parent_id')
                                        <div class="d-block invalid-feedback">{{ $message }}</div>
                                    @enderror
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-6">
                                <button type="submit" class="btn btn-sm btn-primary">Ubah</button>
                                <a href="{{route('galeries.index')}}" class="btn btn-sm btn-secondary">Kembali</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/dashboard/images/index.blade.php
@extends('layouts.app')
@section('title', 'Galery')

@section('title-header', 'Galery')
@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{ route('home') }}">Dashboard</a></li>
    <li class="breadcrumb-item active">Galery</li>
@endsection

@section('action_btn')
    <a href="{{route('galeries.create')}}" class="btn btn-default">Tambah Data</a>
@endsection

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card shadow">
                <div class="card-header bg-transparent border-0 text-dark">
                    <h2 class="card-title h3">Galery</h2>
                    <div class="table-responsive">
                        <table class="table table-flush table-hover">
                            <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Title</th>
                                    <th>Description</th>
                                    <th>Media</th>
                                    <th>Parent</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse ($images as $item)
                                    <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td>{{ $item->title ?? '-' }}</td>
                                        <td>{{ $item->description ?? '-' }}</td>
                                        <td>
                                            <img src="{{ asset('/uploads/images/'.$item->media) }}" alt="{{ $item->title }}" width="100">
                                        </td>
                                        <td>
                                            @php
                                                $modelImage = new App\Models\Image;
                                                $parent = 'No parent';
                                                if($item->parent_id != null){
                                                    $parent = $modelImage->findOrFail($item->parent_id);
                                                    $parent = $parent->title;
                                                }
                                            @endphp
                                            {{$parent}}
                                        </td>
                                        <td class="d-flex jutify-content-center">
                                            <a href="{{route('galeries.edit', $item->id)}}" class="btn btn-sm btn-warning"><i class="fas fa-pencil-alt"></i></a>
                                            <form id="delete-form-{{ $item->id }}" action="{{ route('galeries.destroy', $item->id) }}" class="d-none" method="post">
                                                @csrf
                                                @method('DELETE')
                                            </form>
                                            <button onclick="deleteForm('{{$item->id}}')" class="btn btn-sm btn-danger"><i class="fas fa-trash"></i></button>
                                        </td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td colspan="3">Tidak ada data</td>
                                    </tr>
                                @endforelse
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th colspan="4">
                                        {{ $images->links() }}
                                    </th>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script>
        function deleteForm(id){
            Swal.fire({
                title: 'Hapus data',
                text: "Anda akan menghapus data!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                cancelButtonText: 'Batal!'
                }).then((result) => {
                if (result.isConfirmed) {
                    $(`#delete-form-${id}`).submit()
                }
            }) 
        }
    </script>
@endsection